import { describe, it, expect } from 'vitest';
import { GameEngine } from '../src/game/engine/GameEngine';
import { createGame } from '../src/game/engine/create-game';
import { classicRules } from '../src/game/rules/ClassicRuleSet';
import { assertInvariants } from '../src/game/state/invariants';
import { players,ready,send,fail,fixed,diceEngine,give,levels,reveal } from './helpers';
const empty={money:0,properties:[],cards:[]};
describe('order and commands',()=>{
  it('rerolls ties only and keeps earlier ranks',()=>{let s=createGame(players.slice(0,3),1,'t');s.random.draws=0;const e=new GameEngine(undefined,fixed(6,6,2,3,3,2,4,5,1,2));s=send(s,{type:'ROLL_ORDER'},'p1',e);s=send(s,{type:'ROLL_ORDER'},'p2',e);s=send(s,{type:'ROLL_ORDER'},'p3',e);expect(s.orderState?.pending).toEqual(['p2','p3']);s=send(s,{type:'ROLL_ORDER'},'p2',e);s=send(s,{type:'ROLL_ORDER'},'p3',e);expect(s.order).toEqual(['p1','p2','p3']);expect(s.phase.kind).toBe('ROLL');});
  it('rejects wrong actor, stale revision and malformed commands atomically',()=>{const s=ready(),before=structuredClone(s);expect(fail(s,{type:'ROLL'},'p2').ok).toBe(false);expect(new GameEngine().execute(s,{actor:'p1',expectedRevision:99,command:{type:'ROLL'}}).ok).toBe(false);expect(fail(s,{type:'BID',amount:NaN}).ok).toBe(false);expect(fail(s,{type:'BUY'}).ok).toBe(false);expect(s).toEqual(before);});
  it('available actions do not consume RNG or mutate state',()=>{const s=ready(),before=structuredClone(s);expect(new GameEngine().getAvailableActions(s,'p1').some(a=>a.command.type==='ROLL')).toBe(true);expect(s).toEqual(before);});
});
describe('movement and turn integration',()=>{
  it('moves, buys and passes the turn',()=>{let s=ready();const e=diceEngine(s,1,2);s=send(s,{type:'ROLL'},'p1',e);expect(s.players[0].position).toBe(3);s=send(s,{type:'BUY'});expect(s.properties[3].owner).toBe('p1');expect(s.players[0].money).toBe(1440);s=send(s,{type:'END_TURN'});expect(s.currentPlayerId).toBe('p2');});
  it('pays GO once when landing exactly on it',()=>{let s=ready();s.players[0].position=37;const e=diceEngine(s,1,2);s=send(s,{type:'ROLL'},'p1',e);expect(s.players[0].position).toBe(0);expect(s.players[0].money).toBe(1700);});
  it('gives another roll after doubles, but not a premature end',()=>{let s=ready();const e=diceEngine(s,3,3);s=send(s,{type:'ROLL'},'p1',e);s=send(s,{type:'BUY'});expect(s.extraRoll).toBe(true);expect(fail(s,{type:'END_TURN'}).ok).toBe(false);expect(new GameEngine().getAvailableActions(s,'p1').some(a=>a.command.type==='ROLL')).toBe(true);});
  it('sends third doubles to jail without GO or landing',()=>{let s=ready();s.doubles=2;s.players[0].position=39;const e=diceEngine(s,1,1);s=send(s,{type:'ROLL'},'p1',e);expect(s.players[0].jailed).toBe(true);expect(s.players[0].position).toBe(10);expect(s.players[0].money).toBe(1500);expect(s.extraRoll).toBe(false);});
  it('charges taxes and does nothing on parking',()=>{let s=ready();let e=diceEngine(s,1,3);s=send(s,{type:'ROLL'},'p1',e);expect(s.players[0].money).toBe(1300);s=ready();s.players[0].position=16;e=diceEngine(s,1,3);s=send(s,{type:'ROLL'},'p1',e);expect(s.players[0].money).toBe(1500);});
  it('moves to jail from its space',()=>{let s=ready();s.players[0].position=27;const e=diceEngine(s,1,2);s=send(s,{type:'ROLL'},'p1',e);expect(s.players[0].jailed).toBe(true);});
});
describe('auction',()=>{
  it('includes the decliner and charges the winner',()=>{let s=ready();s.phase={kind:'BUY',player:'p1',property:3};s=send(s,{type:'DECLINE'});s=send(s,{type:'BID',amount:10},'p1');s=send(s,{type:'BID',amount:25},'p2');s=send(s,{type:'LEAVE_AUCTION'},'p1');expect(s.properties[3].owner).toBe('p2');expect(s.players[1].money).toBe(1475);expect(s.phase.kind).toBe('MANAGE');});
  it('does not award free property to the last player',()=>{let s=ready();s.phase={kind:'BUY',player:'p1',property:3};s=send(s,{type:'DECLINE'});s=send(s,{type:'LEAVE_AUCTION'},'p1');expect(s.phase.kind).toBe('AUCTION');s=send(s,{type:'LEAVE_AUCTION'},'p2');expect(s.properties[3].owner).toBe(null);});
  it('rejects unaffordable and non-increasing bids',()=>{let s=ready();s.phase={kind:'BUY',player:'p1',property:3};s=send(s,{type:'DECLINE'});expect(fail(s,{type:'BID',amount:1501}).ok).toBe(false);s=send(s,{type:'BID',amount:10});expect(fail(s,{type:'BID',amount:10}).ok).toBe(false);});
});
describe('rent',()=>{
  it('transfers rent between two players',()=>{let s=ready();give(s,'p2',3);const e=diceEngine(s,1,2);s=send(s,{type:'ROLL'},'p1',e);expect(s.players.map(p=>p.money)).toEqual([1496,1504]);});
  it('calculates hotels, railroads and utilities',()=>{const s=ready();give(s,'p1',1,3,5,15,25,35,12,28);levels(s,{1:5,3:5});expect(classicRules.rent(s,3,8,'NORMAL')).toBe(450);expect(classicRules.rent(s,5,8,'NORMAL')).toBe(200);expect(classicRules.rent(s,12,8,'NORMAL')).toBe(80);s.properties[5].mortgaged=true;expect(classicRules.rent(s,5,8,'NORMAL')).toBe(0);expect(classicRules.rent(s,15,8,'NORMAL')).toBe(200);});
});
describe('buildings and mortgages',()=>{
  it('requires a monopoly and even construction',()=>{let s=ready();give(s,'p1',1);expect(fail(s,{type:'BUILD',property:1}).ok).toBe(false);give(s,'p1',3);s=send(s,{type:'BUILD',property:1});expect(s.bank.houses).toBe(31);expect(fail(s,{type:'BUILD',property:1}).ok).toBe(false);expect(fail(s,{type:'MORTGAGE',property:3}).ok).toBe(false);s=send(s,{type:'BUILD',property:3});assertInvariants(s,classicRules);});
  it('builds a hotel and sells it back to four houses',()=>{let s=ready();give(s,'p1',1,3);levels(s,{1:4,3:4});s=send(s,{type:'BUILD',property:1});expect(s.bank).toEqual({houses:28,hotels:11});expect(s.properties[1].level).toBe(5);s=send(s,{type:'SELL',property:1});expect(s.properties[1].level).toBe(4);expect(s.bank).toEqual({houses:24,hotels:12});});
  it('enforces even selling and permits group liquidation',()=>{let s=ready();give(s,'p1',1,3);levels(s,{1:3,3:2});expect(fail(s,{type:'SELL',property:3}).ok).toBe(false);s=send(s,{type:'SELL_GROUP',group:'brown'});expect(s.bank.houses).toBe(32);expect(s.players[0].money).toBe(1625);});
  it('mortgages and redeems with interest',()=>{let s=ready();give(s,'p1',1);s=send(s,{type:'MORTGAGE',property:1});expect(s.players[0].money).toBe(1530);expect(fail(s,{type:'MORTGAGE',property:1}).ok).toBe(false);s=send(s,{type:'REDEEM',property:1});expect(s.players[0].money).toBe(1497);});
});
describe('jail',()=>{
  it('pays fine before an ordinary roll',()=>{let s=ready();s.players[0].jailed=true;s.players[0].position=10;s.phase={kind:'JAIL'};s=send(s,{type:'PAY_FINE'});expect(s.players[0].money).toBe(1450);expect(s.phase.kind).toBe('ROLL');});
  it('leaves with doubles without granting another roll',()=>{let s=ready();s.players[0].jailed=true;s.players[0].position=10;s.phase={kind:'JAIL'};const e=diceEngine(s,3,3);s=send(s,{type:'JAIL_ROLL'},'p1',e);expect(s.players[0].jailed).toBe(false);expect(s.players[0].position).toBe(16);expect(s.extraRoll).toBe(false);});
  it('pauses mandatory third fine and resumes using original dice',()=>{let s=ready();s.players[0].jailed=true;s.players[0].jailAttempts=2;s.players[0].money=0;s.players[0].position=10;s.phase={kind:'JAIL'};give(s,'p1',5);const e=diceEngine(s,1,2);s=send(s,{type:'JAIL_ROLL'},'p1',e);expect(s.phase.kind).toBe('DEBT');expect(s.players[0].position).toBe(10);s=send(s,{type:'MORTGAGE',property:5});s=send(s,{type:'SETTLE_DEBT'});expect(s.players[0].position).toBe(13);expect(s.players[0].money).toBe(50);expect(s.players[0].jailed).toBe(false);});
  it('uses and returns a held jail card',()=>{let s=ready();reveal(s,'CHANCE-8');s=send(s,{type:'ACK_CARD'});s.players[0].jailed=true;s.players[0].position=10;s.phase={kind:'JAIL'};s=send(s,{type:'USE_CARD',card:'CHANCE-8'});expect(s.heldCards).toHaveLength(0);expect(s.decks.CHANCE.at(-1)).toBe('CHANCE-8');});
});
describe('cards',()=>{
  it('moves to GO and pays once',()=>{let s=ready();s.players[0].position=22;reveal(s,'CHANCE-0');s=send(s,{type:'ACK_CARD'});expect(s.players[0].position).toBe(0);expect(s.players[0].money).toBe(1700);});
  it('moves backward into another deck',()=>{let s=ready();s.players[0].position=36;reveal(s,'CHANCE-9');s=send(s,{type:'ACK_CARD'});expect(s.players[0].position).toBe(33);expect(s.phase.kind).toBe('CARD');expect(s.players[0].money).toBe(1500);});
  it('applies city chest income and tax-like expense',()=>{let s=ready();reveal(s,'CHEST-1');s=send(s,{type:'ACK_CARD'});expect(s.players[0].money).toBe(1700);reveal(s,'CHEST-2');s=send(s,{type:'ACK_CARD'});expect(s.players[0].money).toBe(1650);});
  it('jails without salary',()=>{let s=ready();s.players[0].position=36;reveal(s,'CHANCE-10');s=send(s,{type:'ACK_CARD'});expect(s.players[0].position).toBe(10);expect(s.players[0].money).toBe(1500);expect(s.players[0].jailed).toBe(true);});
  it('counts hotels separately for repairs',()=>{let s=ready();give(s,'p1',1,3);levels(s,{1:5,3:4});reveal(s,'CHANCE-11');s=send(s,{type:'ACK_CARD'});expect(s.players[0].money).toBe(1300);});
  it('doubles railroad rent for nearest railroad card',()=>{let s=ready();s.players[0].position=7;give(s,'p2',15);reveal(s,'CHANCE-4');s=send(s,{type:'ACK_CARD'});expect(s.players[0].money).toBe(1450);});
});
describe('trade',()=>{
  it('swaps money and properties atomically',()=>{let s=ready();give(s,'p1',1);give(s,'p2',3);s=send(s,{type:'CREATE_TRADE',recipient:'p2',offer:{...empty,money:100,properties:[1]},request:{...empty,properties:[3]},proposerChoices:{}});s=send(s,{type:'ACCEPT_TRADE',choices:{}},'p2');expect(s.properties[1].owner).toBe('p2');expect(s.properties[3].owner).toBe('p1');expect(s.players.map(p=>p.money)).toEqual([1400,1600]);expect(s.phase.kind).toBe('ROLL');});
  it('charges receiving mortgage interest and later redemption interest',()=>{let s=ready();give(s,'p1',1);s.properties[1].mortgaged=true;s=send(s,{type:'CREATE_TRADE',recipient:'p2',offer:{...empty,properties:[1]},request:empty,proposerChoices:{}});s=send(s,{type:'ACCEPT_TRADE',choices:{}},'p2');expect(s.players[1].money).toBe(1497);s=send(s,{type:'REDEEM',property:1},'p2');expect(s.players[1].money).toBe(1464);});
  it('rejects trading built groups and unaffordable final balances',()=>{let s=ready();give(s,'p1',1,3);levels(s,{1:1,3:0});expect(fail(s,{type:'CREATE_TRADE',recipient:'p2',offer:{...empty,properties:[3]},request:empty,proposerChoices:{}}).ok).toBe(false);s=ready();s=send(s,{type:'CREATE_TRADE',recipient:'p2',offer:{...empty,money:2000},request:empty,proposerChoices:{}});const snapshot=structuredClone(s);expect(fail(s,{type:'ACCEPT_TRADE',choices:{}},'p2').ok).toBe(false);expect(s).toEqual(snapshot);});
});
describe('debt, bankruptcy and victory',()=>{
  it('does not auto-bankrupt; can raise money and settle',()=>{let s=ready();s.players[0].money=0;give(s,'p1',5);s.phase={kind:'DEBT',debt:{debtor:'p1',creditor:'BANK',amount:80,reason:'test'}};expect(fail(s,{type:'BANKRUPT'}).ok).toBe(false);s=send(s,{type:'MORTGAGE',property:5});s=send(s,{type:'SETTLE_DEBT'});expect(s.players[0].money).toBe(20);expect(s.phase.kind).toBe('MANAGE');});
  it('transfers assets to a creditor and declares a winner',()=>{let s=ready();give(s,'p1',1);s.players[0].money=10;s.phase={kind:'DEBT',debt:{debtor:'p1',creditor:'p2',amount:200,reason:'rent'}};s=send(s,{type:'BANKRUPT'});expect(s.players[0].bankrupt).toBe(true);expect(s.properties[1].owner).toBe('p2');expect(s.winner).toBe('p2');});
  it('auctions assets returned to the bank and continues with three players',()=>{let s=ready(3);give(s,'p1',1);s.players[0].money=0;s.phase={kind:'DEBT',debt:{debtor:'p1',creditor:'BANK',amount:200,reason:'tax'}};s=send(s,{type:'BANKRUPT'});expect(s.phase.kind).toBe('AUCTION');s=send(s,{type:'BID',amount:10},'p2');s=send(s,{type:'LEAVE_AUCTION'},'p3');expect(s.properties[1].owner).toBe('p2');expect(s.currentPlayerId).toBe('p2');expect(s.winner).toBe(null);});
  it('delays victory until inherited mortgage fees are settled',()=>{let s=ready();give(s,'p1',1);s.properties[1].mortgaged=true;s.players[0].money=0;s.phase={kind:'DEBT',debt:{debtor:'p1',creditor:'p2',amount:100,reason:'rent'}};s=send(s,{type:'BANKRUPT'});expect(s.winner).toBe(null);expect(s.phase.kind).toBe('MORTGAGE_TRANSFER');s=send(s,{type:'MORTGAGE_CHOICE',choice:'KEEP'},'p2');expect(s.players[1].money).toBe(1497);expect(s.winner).toBe('p2');});
});
